// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Browser-side client — uses VITE_ prefixed vars injected by Vite at build time.
// During SSR/module-runner evaluation, import.meta.env.VITE_* may be empty,
// so fall back to the process.env vars injected by vite.config.ts define block.
const SUPABASE_URL =
  (import.meta.env.VITE_SUPABASE_URL as string) ||
  (typeof process !== "undefined" && process.env.SUPABASE_URL) ||
  "";
const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string) ||
  (typeof process !== "undefined" && process.env.SUPABASE_PUBLISHABLE_KEY) ||
  "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});