/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FolderAnalysisRouteImport } from './routes/folder-analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApiAnalyserRouteImport } from './routes/api-analyser'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReviewsNewRouteImport } from './routes/reviews.new'
import { Route as ReviewsIdRouteImport } from './routes/reviews.$id'
import { Route as ReviewIdRouteImport } from './routes/review.$id'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as FolderAnalysisIdRouteImport } from './routes/folder-analysis_.$id'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminCreditsRouteImport } from './routes/admin/credits'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as WorkspaceOwnerRepoRouteImport } from './routes/workspace.$owner.$repo'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderAnalysisRoute = FolderAnalysisRouteImport.update({
  id: '/folder-analysis',
  path: '/folder-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyserRoute = ApiAnalyserRouteImport.update({
  id: '/api-analyser',
  path: '/api-analyser',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIdRoute = ReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderAnalysisIdRoute = FolderAnalysisIdRouteImport.update({
  id: '/folder-analysis_/$id',
  path: '/folder-analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsRoute = AdminCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const WorkspaceOwnerRepoRoute = WorkspaceOwnerRepoRouteImport.update({
  id: '/workspace/$owner/$repo',
  path: '/workspace/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-analyser': typeof ApiAnalyserRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/folder-analysis': typeof FolderAnalysisRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/folder-analysis/$id': typeof FolderAnalysisIdRoute
  '/r/$token': typeof RTokenRoute
  '/review/$id': typeof ReviewIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/workspace/$owner/$repo': typeof WorkspaceOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-analyser': typeof ApiAnalyserRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/folder-analysis': typeof FolderAnalysisRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/folder-analysis/$id': typeof FolderAnalysisIdRoute
  '/r/$token': typeof RTokenRoute
  '/review/$id': typeof ReviewIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/admin': typeof AdminIndexRoute
  '/workspace/$owner/$repo': typeof WorkspaceOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-analyser': typeof ApiAnalyserRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/folder-analysis': typeof FolderAnalysisRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/folder-analysis_/$id': typeof FolderAnalysisIdRoute
  '/r/$token': typeof RTokenRoute
  '/review/$id': typeof ReviewIdRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/workspace/$owner/$repo': typeof WorkspaceOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-analyser'
    | '/blog'
    | '/dashboard'
    | '/folder-analysis'
    | '/login'
    | '/pricing'
    | '/admin/blog'
    | '/admin/credits'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/folder-analysis/$id'
    | '/r/$token'
    | '/review/$id'
    | '/reviews/$id'
    | '/reviews/new'
    | '/admin/'
    | '/workspace/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-analyser'
    | '/blog'
    | '/dashboard'
    | '/folder-analysis'
    | '/login'
    | '/pricing'
    | '/admin/blog'
    | '/admin/credits'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/folder-analysis/$id'
    | '/r/$token'
    | '/review/$id'
    | '/reviews/$id'
    | '/reviews/new'
    | '/admin'
    | '/workspace/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-analyser'
    | '/blog'
    | '/dashboard'
    | '/folder-analysis'
    | '/login'
    | '/pricing'
    | '/admin/blog'
    | '/admin/credits'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/blog_/$slug'
    | '/folder-analysis_/$id'
    | '/r/$token'
    | '/review/$id'
    | '/reviews/$id'
    | '/reviews/new'
    | '/admin/'
    | '/workspace/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiAnalyserRoute: typeof ApiAnalyserRoute
  BlogRoute: typeof BlogRoute
  DashboardRoute: typeof DashboardRoute
  FolderAnalysisRoute: typeof FolderAnalysisRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FolderAnalysisIdRoute: typeof FolderAnalysisIdRoute
  RTokenRoute: typeof RTokenRoute
  ReviewIdRoute: typeof ReviewIdRoute
  ReviewsIdRoute: typeof ReviewsIdRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
  WorkspaceOwnerRepoRoute: typeof WorkspaceOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder-analysis': {
      id: '/folder-analysis'
      path: '/folder-analysis'
      fullPath: '/folder-analysis'
      preLoaderRoute: typeof FolderAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-analyser': {
      id: '/api-analyser'
      path: '/api-analyser'
      fullPath: '/api-analyser'
      preLoaderRoute: typeof ApiAnalyserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$id': {
      id: '/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof ReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder-analysis_/$id': {
      id: '/folder-analysis_/$id'
      path: '/folder-analysis/$id'
      fullPath: '/folder-analysis/$id'
      preLoaderRoute: typeof FolderAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credits': {
      id: '/admin/credits'
      path: '/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminCreditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workspace/$owner/$repo': {
      id: '/workspace/$owner/$repo'
      path: '/workspace/$owner/$repo'
      fullPath: '/workspace/$owner/$repo'
      preLoaderRoute: typeof WorkspaceOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCreditsRoute: typeof AdminCreditsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminCreditsRoute: AdminCreditsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiAnalyserRoute: ApiAnalyserRoute,
  BlogRoute: BlogRoute,
  DashboardRoute: DashboardRoute,
  FolderAnalysisRoute: FolderAnalysisRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  BlogSlugRoute: BlogSlugRoute,
  FolderAnalysisIdRoute: FolderAnalysisIdRoute,
  RTokenRoute: RTokenRoute,
  ReviewIdRoute: ReviewIdRoute,
  ReviewsIdRoute: ReviewsIdRoute,
  ReviewsNewRoute: ReviewsNewRoute,
  WorkspaceOwnerRepoRoute: WorkspaceOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
